added a staging action

diff --git a/.github/workflows/BuildGodot.yaml b/.github/workflows/BuildGodot.yaml
--- a/.github/workflows/BuildGodot.yaml
+++ b/.github/workflows/BuildGodot.yaml
@@ -1,9 +1,15 @@
-name: "Godot->GHPages"
+name: "BuildGodot->GHPages"
 
 on:
-  push:
-    branches: [release]
-  workflow_dispatch:
+  workflow_call:
+    inputs:
+      sub_build_path:
+        required: false
+        type: string
+        default: ""
+    secrets:
+      GITHUB_TOKEN:
+        required: true
 
 env:
   GODOT_VERSION: 3.4.1
@@ -23,16 +29,28 @@ jobs:
         run: |
           mkdir -v -p ~/.local/share/godot/templates
           mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
+      - name: Install Necessary Software
+        run: |
+          apt-get update && apt-get install -y --no-install-recommends sed 
       - name: Web Build
         run: |
-          mkdir -v -p build/web
-          godot -v --export "HTML5" ../build/web/index.html
+          mkdir -v -p build/web${{inputs.sub_build_path}}/web && \
+          godot -v --export "HTML5" build/web${{inputs.sub_build_path}}/index.html || true && \
+          echo "built godot"
+      - name: Copy static files
+        run: |
+          cp -r html_export/static/* build/web${{inputs.sub_build_path}} && \
+          echo "copied files"
+      - name: Add Git Hash to build
+        run: |
+          cd build/web${{inputs.sub_build_path}}
+          sed -i "s@>branch and commit hash<@>$GITHUB_REF:$GITHUB_SHA<@" index.html && \
+          echo "added commit hash to index.html" || echo "failed to add the commit hash"
       - name: Upload Artifact
         uses: actions/upload-artifact@v1
         with:
           name: web
           path: build/web
-      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
       - name: Install rsync 📚
         run: |
           apt-get update && apt-get install -y rsync
